[package]
name = "svgx"
version = "0.1.0"
edition = "2021"

[dependencies]
xmlparser = "0.13"
clap = { version = "4.4", features = ["derive"] }
indexmap = "2.1"
regex = "1.12.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench_main"
harness = false
